### ISSUE TITLE
Introduce Regions

### ISSUE THREAD

**Issue by rgaudin** [kiwix/mirrors-qa#38]
Following https://github.com/kiwix/container-images/issues/263, we've decided that we will be configuring mirrorbrain mostly via the `regionOnly` parameter.

In order to generate region-aware data, we need our Countries to be associated with regions.

We will use the Maxmind GeoIP Countries DB for that (because that's stable and because that's what MB is already using – albeit an older version)

**Todo:**

- [x] Add region Table (code, name)
- [x] Add region field in Country
- [x] Write a script that given a `GeoLite2-Country-Locations-en.csv` file fills both the region table and updates the countries.

DB file can be downloaded from [maxmind website](https://www.maxmind.com/en/geoip2-country-database) (requires creating an account). What's most appropriate I believe is the `GeoLite2 Country: CSV Format` download and the `GeoLite2-Country-Locations-en.csv` inside it.
